set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[0]}]
set_property PACKAGE_PIN H5 [get_ports {mode_led[5]}]
set_property PACKAGE_PIN K6 [get_ports {mode_led[3]}]
set_property PACKAGE_PIN J5 [get_ports {mode_led[4]}]
set_property PACKAGE_PIN M1 [get_ports {mode_led[1]}]
set_property PACKAGE_PIN L1 [get_ports {mode_led[2]}]
set_property PACKAGE_PIN K3 [get_ports {mode_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN R17 [get_ports first_level_button]
set_property IOSTANDARD LVCMOS33 [get_ports first_level_button]
set_property PACKAGE_PIN R11 [get_ports power_menu_button]
set_property IOSTANDARD LVCMOS33 [get_ports power_menu_button]
set_property PACKAGE_PIN R15 [get_ports second_level_button]
set_property IOSTANDARD LVCMOS33 [get_ports second_level_button]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN V1 [get_ports self_clean_button]
set_property IOSTANDARD LVCMOS33 [get_ports self_clean_button]
set_property PACKAGE_PIN U4 [get_ports third_level_button]
set_property IOSTANDARD LVCMOS33 [get_ports third_level_button]
set_property PACKAGE_PIN P15 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports light_switch]
set_property IOSTANDARD LVCMOS33 [get_ports lighting_func]
set_property PACKAGE_PIN M4 [get_ports light_switch]
set_property PACKAGE_PIN K1 [get_ports lighting_func]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports display_switch1]
set_property IOSTANDARD LVCMOS33 [get_ports display_switch2]
set_property PACKAGE_PIN P5 [get_ports display_switch1]
set_property PACKAGE_PIN P4 [get_ports display_switch2]
set_property PACKAGE_PIN G2 [get_ports {seg_en[7]}]
set_property PACKAGE_PIN C2 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN C1 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN H1 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN G1 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN F1 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN E1 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN G6 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN B4 [get_ports {seg_out1[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_out1[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_out1[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_out1[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_out1[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_out1[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_out1[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_out1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[6]}]
set_property PACKAGE_PIN H6 [get_ports {mode_led[6]}]


set_property IOSTANDARD LVCMOS33 [get_ports gesture_time_set_switch]
set_property IOSTANDARD LVCMOS33 [get_ports reminder_duration_set_switch]
set_property IOSTANDARD LVCMOS33 [get_ports current_time_set_switch]
set_property PACKAGE_PIN P3 [get_ports current_time_set_switch]
set_property PACKAGE_PIN R2 [get_ports gesture_time_set_switch]
set_property PACKAGE_PIN P2 [get_ports reminder_duration_set_switch]

set_property IOSTANDARD LVCMOS33 [get_ports clean_warning_light]
set_property PACKAGE_PIN K2 [get_ports clean_warning_light]

set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property PACKAGE_PIN T4 [get_ports tx]


set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out2[0]}]
set_property PACKAGE_PIN D4 [get_ports {seg_out2[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_out2[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_out2[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_out2[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_out2[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_out2[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_out2[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_out2[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports manual_clean]
set_property PACKAGE_PIN R1 [get_ports manual_clean]
